### ISSUE TITLE
Gracefully handle errors returned from pusher

### ISSUE THREAD

**Issue by msmykowski** [edgurgel/pusher#7]
Occasionally pusher will respond with an error rather than the expected body.  e.g. "The data content of this event exceeds the allowed maximum (10240 bytes). See http://pusher.com/docs/server_api_guide/server_publishing_events for more info\n".  Currently when this happens, the body will be decoded as though it were JSX (https://github.com/edgurgel/pusher/blob/master/lib/pusher/http_client.ex#L14), causing the process to crash.  Instead, it would be nice if the error were handled gracefully.

**Comment by edgurgel** [comment]
Yeah agreed 👍

**Comment by jonas-zipprick** [comment]
Jep, caused my process to crash too.
Would have been hard to figure out if i wouldn't have found this open issue.
