### ISSUE TITLE
Req for information: configuration settings for bitstamp

### ISSUE THREAD

**Issue by cruppstahl** [edgurgel/pusher#9]
Hi,

this is not a bug report, but I'm stuck with using pusher from elixir, and have not been able to find help elsewhere. I try to connect to bitstamp's API to get realtime bitcoin trading information. But I don't know how to configure the Pusher library in order to connect.

`Pusher.configure!` requires the following parameters:

1. server name ("ws.pusherapp.com")
2. port (443)
3. "app_id"
4. "app_key" ("de504dc5763aeef9ff52")
5. "secret"

I know 1, 2, 4, but I have not been able to figure out 3 and 5. Can you help with this?

    iex(1)> Pusher.configure!("ws.pusherapp.com", 443, "", "de504dc5763aeef9ff52", "")
    :ok
    iex(2)> Pusher.channels
    ** (HTTPoison.Error) :closed
        lib/pusher/http_client.ex:2: Pusher.HttpClient.request!/5
        lib/pusher.ex:33: Pusher.channels/0

Thanks
Christoph

**Comment by edgurgel** [comment]
You should probably contact Pusher support. I'm afraid I can't really help you :/
